<?php
return [
    'admin' => [
        'name' => 'Administrator TI',
        'description' => 'Los usuarios administradores pueden realizar cualquier acción.',
        'permissions' => [
            'create_patient',
            'edit_patient',
            'show_patient',
            'delete_patient',
            'create_medical_record',
            'edit_medical_record',
            'show_medical_record',
            'delete_medical_record',
            'create_photographic_evidence',
            'edit_photographic_evidence',
            'show_photographic_evidence',
            'delete_photographic_evidence',
            'create_clinical_staff',
            'edit_clinical_staff',
            'show_clinical_staff',
            'delete_clinical_staff',
            'create_notes',
            'edit_notes',
            'show_notes',
            'delete_notes',
        ],
    ],
    'admin_kura' => [
        'name' => 'Administrador Kura+',
        'description' => 'Administra módulo Kura+: lectura general, edita notas y puede borrar evidencia fotográfica.',
        'permissions' => [
            'show_patient',
            'show_medical_record',
            'show_photographic_evidence',
        ],
    ],
    'resp_sitio' => [
        'name' => 'Responsable del sitio',
        'description' => 'Puede ver pacientes y personal clínico, revisar notas, y borrar evidencia fotográfica.',
        'permissions' => [
            'show_patient',
            'show_clinical_staff',
            'show_medical_record',
            'show_photographic_evidence',
            'show_notes',
            'delete_photographic_evidence',
        ],
    ],
    'perfil_operativo' => [
        'name' => 'Perfil operativo',
        'description' => 'Ve y da seguimiento; no borra pacientes ni fotos.',
        'permissions' => [
            'create_patient',
            'edit_patient',
            'show_patient',
            'create_medical_record',
            'edit_medical_record',
            'show_medical_record',
            'create_photographic_evidence',
            'edit_photographic_evidence',
            'show_photographic_evidence',
            'create_notes',
            'edit_notes',
            'show_notes',
        ],
    ],
];
